CREATE TABLE IF NOT EXISTS app_data_revision (
  id TINYINT UNSIGNED PRIMARY KEY,
  revision BIGINT UNSIGNED NOT NULL DEFAULT 0,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

INSERT INTO app_data_revision (id, revision)
VALUES (1, 0)
ON DUPLICATE KEY UPDATE id = VALUES(id);
